# Disable automatic runs of this pipeline when changes are pushed to the repository.
trigger: none

# Disable automatic runs of this pipeline when a PR is create.
pr: none

# Add the pipeline that builds the packages as a resource.
# This allows the deployment pipeline to be triggered whenever
# the build pipeline completes.
resources:
  pipelines:
  - pipeline: build-pipeline   # The name for the triggering build pipeline within this script
    source: device-detection-nginx-tag-repository # Name of the pipeline from here: https://51degrees.visualstudio.com/Pipeline/_build
    trigger: true
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository

# Include shared variables
variables:
- template: shared-variables.yml

stages:
- template: shared-publish-github-stage.yml@ciTemplates
  parameters:
    imageName: $(linux18Image)
    branchName: 'refs/heads/main'