name: Monthly Copyright Update

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so quote this string
    - cron:  '0 0 1 * *'

jobs:
  # Run the common workflow on each pull request
  Monthly_Copyright_Update:
    uses: 51Degrees/common-ci/.github/workflows/monthly-copyright-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
