name: Nightly Publish Main

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Nightly PRs to Main]
    types: [completed]

jobs:
  # Run the common workflow to test and publish the main branch
  Nightly_Publish_Main:
    uses: 51Degrees/common-ci/.github/workflows/nightly-publish-main.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      build-platform: ubuntu-latest
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.DEVICE_DETECTION_URL }}
      NginxKey: ${{ secrets.NGINX_PLUS_KEY }}
      NginxCert: ${{ secrets.NGINX_PLUS_CERT }}
